apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: keycloak-proxy
    yuuvis: "true"
  name: keycloak-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: keycloak-proxy
  type: ClusterIP