apiVersion: v1
data:
  keycloak-proxy.yml: |
    spring.security.user.name: {{.Values.yuuvis.keycloak.proxy.user}}
    spring.security.user.password: {{.Values.yuuvis.keycloak.proxy.password}}

    logging:
      level:
        root: INFO
        com.os.services.keycloak: DEBUG

    keycloak-proxy.instances:
    - serverUrl: https://{{.Values.yuuvis.keycloak.instance.address}}/auth
      username: {{.Values.yuuvis.keycloak.instance.user}}
      password: {{.Values.yuuvis.keycloak.instance.password}}
kind: ConfigMap
metadata:
  name: keycloak-proxy-yml-configmap
