apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: check-job-status
  name: check-job-status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: check-job-status
  name: check-job-status
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: check-job-status
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: check-job-status
subjects:
- kind: ServiceAccount
  name: check-job-status
  namespace: yuuvis
