apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: check-job-status
  name: check-job-status-{{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: check-job-status
  name: check-job-status-{{.Release.Namespace}}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: check-job-status-{{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: check-job-status-{{.Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: check-job-status-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
