apiVersion: v1
data:
  keycloak-proxy.yml: |
    keycloak-proxy.instances:
    - serverUrl: https://{{.Values.yuuvis.keycloak.instance.address}}/auth
      username: {{.Values.yuuvis.keycloak.instance.user}}
      password: {{.Values.yuuvis.keycloak.instance.password}}
kind: ConfigMap
metadata:
  name: keycloak-proxy-yml-configmap
