apiVersion: v1
kind: Secret
metadata:
  name: keycloakuser
type: Opaque
data:
  user: {{ .Values.yuuvis.keycloak.instance.user | b64enc | quote }}
  password: {{ .Values.yuuvis.keycloak.instance.password | b64enc | quote }}
  