apiVersion: v1
kind: Secret
metadata:
  name: keycloak-proxy-secret
type: Opaque
data:
  user: {{.Values.yuuvis.keycloak.proxy.user | b64enc | quote }}
  password: {{.Values.yuuvis.keycloak.proxy.password | b64enc | quote }}