apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: keycloak-proxy
  name: keycloak-proxy
spec:
  selector:
    matchLabels:
      name: keycloak-proxy
      yuuvislog: "true"
  template:
    metadata:
      labels:
        name: keycloak-proxy
        yuuvislog: "true"
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-proxy
        image: busybox
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
        imagePullPolicy: IfNotPresent      
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configservice/config
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              key: user
              name: keycloak-proxy-secret
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-proxy-secret
        image: {{.Values.yuuvis.keycloak.proxy.image }}
        imagePullPolicy: IfNotPresent
        name: keycloak-proxy
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: yuuvisorg
      restartPolicy: Always