apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: check-job-status
  name: check-job-status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: check-job-status
  name: check-job-status
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: check-job-status
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: check-job-status
subjects:
- kind: ServiceAccount
  name: check-job-status
  namespace: {{.Release.Namespace}}
