imageCredentials:
  yuuvisorg:
    registry: docker.yuuvis.org
    username:
    password:

yuuvis:
  db:
    user: postgres
    password: changeme
  keycloak:
    instance:
      #Increment with each additional instance
      address: auth2.example.net
      user: changeme
      password: changeme
    db:
      name: keycloak_instance_2
      user: keycloak
      password: changeme
  git:
    protocol: http
    url: gogs.infrastructure/yuuvis/yuuvis-config.git
    server: gogs.infrastructure
    name: yuuvis-config
    user: yuuvis
    password: changeme
    branch: master

keycloak:
  enabled: true
  fullnameOverride: "keycloak"
  image.repository: docker.yuuvis.org/yuuvis/keycloak
  #Image tag is reverting to jboss repo, requring manual change:
  #kubectl edit sts keycloak -n infrastructure
  #image:docker.yuuvis.org/yuuvis/keycloak/15.0.2-stable1
  image.tag: "15.0.2"
  imagePullSecrets: 
    - name: dockeryuuvisorg
  livenessProbe: |
    httpGet:
      path: /auth/
      port: http
    initialDelaySeconds: 600
    timeoutSeconds: 5
  postgresql:
    enabled: false
  extraEnv: |
    - name: KEYCLOAK_USER_FILE
      value: /secrets/keycloak/user
    - name: KEYCLOAK_PASSWORD_FILE
      value: /secrets/keycloak/password
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: postgresql
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER_FILE
      value: /secrets/db-creds/user
    - name: DB_PASSWORD_FILE
      value: /secrets/db-creds/password
    - name: JGROUPS_DISCOVERY_PROTOCOL
      value: dns.DNS_PING
    - name: JGROUPS_DISCOVERY_PROPERTIES
      value: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
    - name: CACHE_OWNERS_COUNT
      value: "2"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "2"
    - name: JAVA_OPTS
      value: >-
        -Djava.net.preferIPv4Stack=true
        -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
        -Djava.awt.headless=true 
        -Djboss.tx.node.name=$HOSTNAME  
  extraVolumes: |
    - name: realm-config
      configMap:
        name: realmconfigmap
    - name: db-creds
      secret:
        secretName: keycloakdb
    - name: kc-creds
      secret:
        secretName: keycloakuser
  extraVolumeMounts: |
    - name: realm-config
      mountPath: "/realm/"
      readOnly: true
    - name: db-creds
      mountPath: /secrets/db-creds
      readOnly: true
    - name: kc-creds
      mountPath: /secrets/keycloak
      readOnly: true
