yuuvis:
  keycloak:
    instance:
      address: kc001.example.net
      user: ${KEYCLOAK_ADMIN_USER}
      password: ${KEYCLOAK_ADMIN_PWD}
    db:
      user: keycloak
      password: ${KEYCLOAK_DB_PWD}
  git:
    user: ${GITUSER}
    password: ${GITPWD}

